task3: task3.cpp
        mpic++ task3.cpp -o task3

run: task3
        mpirun -np 8 ./task3 26 0 1
        mpirun -np 16 ./task3 26 0 1
        mpirun -np 32 ./task3 26 0 1
        mpirun -np 64 ./task3 26 0 1

